[package]
name = "sanitizeable"
version = "0.1.0"
authors = ["soruh <mail@soruh.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sanitizeable_derive = { path = "../sanitizeable_derive" }